### ISSUE TITLE
`compile` option not working.

### ISSUE THREAD

**Issue by funyapu** [pxgrid/aigis#100]
I want to compile my jade code in comment with compile option had settled,
though it not works.

So tested your example as above and also not working.
1. Open `node_modules/node-aigis/examples/css/style.css `
1. Add `compile: true` on note of button.
1. run `./node_modules/.bin/aigis run -c ./node_modules/node-aigis/examples/aigis_config.yml `
<img width="589" alt="2016-12-02 20 47 01" src="https://cloud.githubusercontent.com/assets/5101532/20833074/11473ca8-b8d1-11e6-8e34-9aa4e04afdb6.png">

**Comment by nakajmg** [comment]
If you want to compile the codeblock, you have to enable transform options in configuration file. 

e.g. You can choose target languages like below:

```yaml
transform:
  - html
  - jade
  - ejs
  - hbs
```

That examples allows only `html` transform.

[/examples/aigis_config.yml#L50](https://github.com/pxgrid/aigis/blob/50594bb9a34255e3e1f4ec44c370a75602e18414/examples/aigis_config.yml#L50)

```yaml
transform:
  - html
#  - jade
#  - ejs
#  - hbs
#  - coffee
```

Could you try to enable transform options.

**Comment by funyapu** [comment]
Sorry. It was my misunderstanding. I expected to get row HTML for code preview w/ this option.
