### ISSUE TITLE
Can't transform jade.

### ISSUE THREAD

**Issue by funyapu** [pxgrid/aigis#101]
My styleguide doesn't offer preview if I use `jade` for describing.
Though works for `node_modules/node-aigis/examples/css/style.css`.

```
node@v7.1.0
node-aigis@1.2.1
```

<img width="1077" alt="2016-12-02 21 10 15" src="https://cloud.githubusercontent.com/assets/5101532/20833607/f3066fc2-b8d3-11e6-92ea-2125ca180ba9.png">
<img width="1036" alt="2016-12-02 21 10 10" src="https://cloud.githubusercontent.com/assets/5101532/20833608/f328a95c-b8d3-11e6-8d02-9427bbe3ef73.png">

* `node_modules/node-aigis/examples/css/style.css`.
<img width="589" alt="2016-12-02 20 47 01" src="https://cloud.githubusercontent.com/assets/5101532/20833643/1472cfa2-b8d4-11e6-8932-017b440ba35b.png">

**Comment by nakajmg** [comment]
I think it same as #100 maybe.

**Comment by funyapu** [comment]
oh.. Never mind. I've found out that was because I had a space between blockquote and syntax name.
<img width="133" alt="2016-12-06 18 27 42" src="https://cloud.githubusercontent.com/assets/5101532/20920012/b79185a6-bbe1-11e6-8e19-ed059e170d77.png">
