### ISSUE TITLE
プレビューが1つしか表示されない

### ISSUE THREAD

**Issue by geckotang** [pxgrid/aigis#14]
/*
    ---
    name: div
    category:
      - module
      - all
    ---
    
    ```html
    <div>1</div>
    ```
    
    ```html
    <div>2</div>
    ```

    */

コードブロック（html）の最初の方だけプレビューが作成される。

![image](https://cloud.githubusercontent.com/assets/683965/8942655/900a1992-35b1-11e5-950b-e2de5747eb3b.png)

**Comment by nakajmg** [comment]
https://github.com/pxgrid/aigis/commit/fb58d3c1e8c3edda57dad01b8b8cd0a7a72b2383
👆で修正

**Comment by geckotang** [comment]
:+1: thanks
