### ISSUE TITLE
プレビューエリアに、ハイライトされたコードが挿入される

### ISSUE THREAD

**Issue by geckotang** [pxgrid/aigis#19]
node v0.12.6
npm 2.13.2
node-aigis 0.1.0

コードフェンス内に書いたHTMLで、インデントが4つある時に、改行するとプレビューエリアにコードが入ってしまう？のかも？

    /*
    ---
    name: test
    category:
      - test
    ---
    
    ```html
      <div>bbb</div>
      <div>aaa</div>
    ```
    
    ```html
      <div>
        <div>bbb</div>
        <div>aaa</div>
      </div>
    ```
    
    ```html
    <div>
      <div>bbb</div>
    
      <div>aaa</div>
    </div>
    ```
    
    ```html
      <div>
        <div>bbb</div>
    
        <div>aaa</div>
      </div>
    ```
    
    */

![image](https://cloud.githubusercontent.com/assets/683965/9026664/ec638c96-3971-11e5-9b9f-76d700dbf952.png)

**Comment by nakajmg** [comment]
```html
<div class='aigis-preview'>
  <div>
    <div>bbb</div>

    <div>aaa</div>
</div>
</div>
```

これがmarkedownに挿入されて、markedでコンパイルされると

```
<div class='aigis-preview'>
  <div>
    <div>bbb</div>

<pre><code>&lt;div&gt;aaa&lt;/div&gt;
</code></pre><p></div>
</div></p>
```

になる。

markedの仕様で`空行の後の4スペでcode`になるッて感じかな。空行削除くらいしか思いつかないけど空行いれたいときもありそうだし。

空行を全角スペースに置換ていうの思いついたけど何か違う気がする。

**Comment by geckotang** [comment]
> 空行を全角スペースに置換ていうの思いついたけど何か違う気がする。

コピペした時に全角になっちゃうからちょっとつらそう

**Comment by nakajmg** [comment]
HTMLとして表示するやつだけコンパイル前に整形かけちゃえばいいかな。コピペは表示されてるコードブロックのほうでやるんだし

**Comment by nakajmg** [comment]
#21 で修正
