### ISSUE TITLE
他モジュールへのリンクを簡単にしたい

### ISSUE THREAD

**Issue by geckotang** [pxgrid/aigis#35]
コメントブロック内でマークダウンの`[表示名][参照先]`を使用したい。

    /*
    ---
    name: moduleA
    category:
      - modules
    ---
    please refer [moduleD][modules/moduleD] :)
    */

参考：https://github.com/trulia/hologram#referencing-other-components

**Comment by nakajmg** [comment]
これはそのモジュールへのリンクが張られるってことで合ってる？
現状モジュール毎に出力されないのと、モジュールに複数のカテゴリが設定されてる場合にどのページにリンク貼ったらいいか解決できなさそう 💭

**Comment by geckotang** [comment]
> これはそのモジュールへのリンクが張られるってことで合ってる？

そうです。

> 現状モジュール毎に出力されないのと、モジュールに複数のカテゴリが設定されてる場合にどのページにリンク貼ったらいいか解決できなさそう 

あー、、確かに。いい案も思いつかないので、自身で相対パスなりのリンクを貼るようにしてみようと思います。
