### ISSUE TITLE
htmlを外部化したい

### ISSUE THREAD

**Issue by geckotang** [pxgrid/aigis#36]
コメントブロックに記述するHTMLの量が長くなってくると、CSSを見るのが辛くなってくるので、HTML部分を外部化できるといいかもしれない。

---

KSSの場合は

```css
// Buttons
//
// A majority of buttons in the site are built from the same base class.
//
// Markup: buttons.html
```

とすると、 `buttons.html` を読み込んでくれる。

---

また、KSSの場合は`hbs`も指定できる。
https://github.com/kss-node/kss-node/blob/master/demo/forms/forms.hbs
`{{> "demo.forms.text.label-pairs" }}` という感じで、カテゴリとモジュール名を指定すると、そのモジュールのHTMLが読み込まれる。
この機能はあっても良いけど、なくてもいいかなと思う。（あったら使う）

**Comment by nakajmg** [comment]
ref: https://github.com/pxgrid/aigis/pull/37
