### ISSUE TITLE
コードプレビュー表示: aigis-codeblock の pre の入れ子

### ISSUE THREAD

**Issue by yomotsu** [pxgrid/aigis#40]
```
<pre>
  <code class="lang-html">
    <div class="aigis-codeblock aigis-codeblock--html">
      <pre class="editor editor-colors">
        <div class="line">...
```
になっていますが、

- code要素はフレージングしか内包できませんつまりdivを入れることはできないため、変えたほうがよさそうです *1
- preが二重になってしまっていました。ひとつでよさそうです

*1: http://www.w3.org/TR/html5/text-level-semantics.html#the-code-element

**Comment by nakajmg** [comment]
markdownのパーサが外側の`pre & code`を作りコードハイライトのライブラリが内側の`pre`を作るので変更するの難しそう💁

**Comment by nakajmg** [comment]
rel: https://github.com/atom/highlights/issues/26
