### ISSUE TITLE
Missing links on gh-pages

### ISSUE THREAD

**Issue by watilde** [pxgrid/aigis#62]
[aigis/docs](http://pxgrid.github.io/aigis/docs/) seems missing link. You can see it is used on the following pages:
+ docs link on http://pxgrid.github.io/aigis/sample/
+ Documents link on http://pxgrid.github.io/aigis/

**Comment by nakajmg** [comment]
@watilde 
Thanks for report!

I fixed it :+1:

**Comment by watilde** [comment]
thanks!
