### ISSUE TITLE
大量のCSSがあった場合になにもされない

### ISSUE THREAD

**Issue by yasupeke** [pxgrid/aigis#64]
大量にCSSがあった場合にlogで
```
[Info] Start: Generate Styleguide
```
は出力されるのですが
```
[Info] Finish: Generate Styleguide
```
が出力されずに終了してしまい出力先になにもできていない状態になってしまいます。
Startのログのあとに16ファイル分のログは出力されています。
through2-filterにhighWaterMark: 16というのがあったので何か関わりがあるのかと思ったのですが深くは追っていないです。

ご確認頂けると幸いです。

**Comment by geckotang** [comment]
@yasupeke Thanks for letting me know.
可能であれば、OS、Nodeやnpmのバージョン、aigisのバージョンをいただけますか？また、ディレクトリ構成やファイルの数など問題ない範囲で教えていただけると助かります。

**Comment by yasupeke** [comment]
@geckotang 返信ありがとうございます。
以下構成になります。

OS: Windows10 Pro 64bit
Node: 4.2.6
npm: 3.8.5
aigis: 1.0.2

ディレクトリ構成
```
D:.
│  style1.css
│  style2.css
│  style3.css
│  style4.css
│  style5.css
├─dir1
│      style6.css
├─dir2
│      style7.css
│      style8.css
│      style9.css
│      style10.css
│
├─dir3
│      style11.css
│      style12.css
├─dir4
│      style13.css
├─dir5
│      style14.css
├─dir6
│      style15.css
│      style16.css
├─dir7
│      style17.css
├─dir8
│      style18.css
├─dir9
│  │  style19.css
│  ├─dir9-1
│  │      style20.css
│  └─dir9-2
│         style21.css
├─dir10
│      style22.css
├─dir11
│      style23.css
│      style24.css
├─dir12
│      style25.css
├─dir13
│      style26.css
├─dir14
│      style27.css
├─dir15
│      style28.css
├─dir16
│      style29.css
├─dir17
│      style30.css
├─dir18
│      style31.css
├─dir19
│      style32.css
├─dir20
│      style33.css
│      style34.css
├─dir21
│      style35.css
├─dir22
│      style36.css
├─dir23
│      style37.css
├─dir24
│      style38.css
├─dir25
│      style39.css
├─dir26
│  ├─dir26-1
│  │      style40.css
│  │      style41.css
│  │      style42.css
│  └─dir26-2
│         style43.css
│         style44.css
│         style45.css
├─dir27
│      style46.css
├─dir28
│  ├─dir28-1
│  │      style47.css
│  │      style48.css
│  │      style49.css
│  │      style50.css
│  ├─dir28-2
│  │      style51.css
│  ├─dir28-3
│  │      style52.css
│  └─dir28-4
│          style53.css
├─dir29
│      style54.css
└─dir30
       style55.css
       style56.css
```

よろしくお願い致します。

**Comment by geckotang** [comment]
@yasupeke node-aigis 1.0.3 にて対応できているはずなので、バージョンを上げて、再度試してもらえますかー？

**Comment by yasupeke** [comment]
@geckotang 
アップデートしようとしたら下記の状態から進まずインストールできません。
調査し確認できたらまたご報告させていただきます。

```
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
extract:lodash -> gentlyR - |#########################################################################----------------|
```

**Comment by yasupeke** [comment]
@geckotang 
nodeのバージョン変えたり同僚に試してもらったりしたのですがwindowsではインストールが止まってしまいました。macでは問題なくインストールできました。

**Comment by geckotang** [comment]
@yasupeke その他エラー文言や、`npm-debug.log`はありますか？
また、Windowsの場合は、 https://github.com/nodejs/node-gyp/issues/629#issuecomment-153196245 なども参考にしてみてください。

**Comment by geckotang** [comment]
@yasupeke 問題の切り分けをしたいので、以下、確認お願いします。

1. Macでは `node-aigis 1.0.3` を使用した際に、大量のCSSでもスタイルガイドは生成される
2. Windowsでは `node-aigis 1.0.3` をインストールする際に、エラーが発生し、インストール出来ない

ということでよいでしょうか？ 1について解決しているようであれば、一旦Issueを閉じて別のIssueを立てます。

**Comment by yasupeke** [comment]
@geckotang 
気が回らずすいません。
現在おっしゃる通りの状態です。
1については、macではnode-aigis@1.0.3でスタイルガイドが出力されました。
2についてはnpm-debug.logはありません。止まってしまいインストールが先に進まない状態になります。(1日放置しましたが進んでいませんでした)

なので、この件にかんしてはcloseで問題ありません。

**Comment by geckotang** [comment]
@yasupeke ありがとうございます。 Windowsでインストール出来ない件に関しては #66 でお願い致します。もし可能であれば https://github.com/pxgrid/aigis/issues/64#issuecomment-214145915 の方法も検討してみてください。
