### ISSUE TITLE
Windowsでインストールが途中で止まる

### ISSUE THREAD

**Issue by geckotang** [pxgrid/aigis#66]
Windowsでは node-aigis 1.0.3 をインストールする際に、エラーが発生し、インストール出来ない

OS: Windows10 Pro 64bit
Node: 4.2.6
npm: 3.8.5
aigis: 1.0.3

**Comment by geckotang** [comment]
refs #64

**Comment by yasupeke** [comment]
@geckotang 
node-gypのエラーに関してはnode-aigis@1.0.2のときにでて、python2.7.11を入れたりして解決はしています。

**Comment by geckotang** [comment]
@yasupeke node-aigis@1.1.0をお試しくださいー。シンタックスハイライターを変更した都合で一部テンプレートファイルなどを修正する必要があるかもしれません。
https://github.com/pxgrid/aigis/commit/0484c59f2bb2c2a3d4e79d79c06525e953f538f7

**Comment by yasupeke** [comment]
@geckotang インストールできました。ご対応ありがとうございました:)

**Comment by geckotang** [comment]
done
