### ISSUE TITLE
Color detecting wrongly detects colors from scss variable names

### ISSUE THREAD

**Issue by jkempff** [pxgrid/aigis#67]
First of all, nice project you have there!

Although, I noticed that e.g.

```scss
$red: #F21;
```

leads to two colors at the "All colors" overview: `red` and `#F21`.

Not a major issue, but it somehow makes the colors list impractical.

**Comment by jkempff** [comment]
I just noticed, this also happens for css class names:

```css
.btn--yellow {
    ..
}
```

..adds the color "yellow" to the list.

**Comment by jkempff** [comment]
The problem seems to be with the `get-css-colors` dependency. It looks to me, as if this project is supposed to find colors from CSS property values, like "color: #ff0" and not entire css files.
Maybe there is an alternative?

**Comment by geckotang** [comment]
@jkempff Thank you for letting me know about the problem. I need to think of alternative ways. Probably , It takes a long time to resolve. 

Old version aigis that used `node-sass` for parsing CSS could correctly build color pallets. However, I would rather not use `node-sass` as much as possible.

**Comment by geckotang** [comment]
@jkempff  Hi, @nakajmg fixed this problem. Please try to use node-aigis@v1.1.2 .
