### ISSUE TITLE
relative path to the src files

### ISSUE THREAD

**Issue by DirtyCheck** [pxgrid/aigis#72]
Hi,

I've have tried to generate style guide with builtin "init" or even from the node-aigis examples folder, but everytime I got the wrong relative path in any sub-folder of components.
**\node_modules\.bin\styleguide\category\module\button\index.html**
`<head>`
`    <meta charset="utf-8">`
`    <meta name="viewport" content="width=device-width">`
`    <link href="../aigis_assets/css/highlight/monokai.css" rel="stylesheet">`
`   <link href="../aigis_assets/css/theme.css" rel="stylesheet">`
`    <link href="../css/style.css" rel="stylesheet">`
`</head>`
but should be `<link href="../../../css/style.css" rel="stylesheet">` for example

Precondition: Everything out of the box, according to the docs - Windows 10

**Comment by u-v** [comment]
i had the same issue, you can check my PR. i hope it'll be merged soon)

**Comment by cyril-lamotte** [comment]
Hi,

I have the same issue. the root var seems to be be wrong.

**Comment by nakajmg** [comment]
Now, #81 was merged. Then this problem was solved 🎉 Please update `node-aigis` to `1.1.5` 🙏 

Sorry for response delay 🙇 We prepared Windows environment that took a lot of time 😂
From now on, we increase Windows compatibility 🙆

**Comment by u-v** [comment]
Thanks! Appreciate your time!
