### ISSUE TITLE
Cannot find module 'lodash/assign'

### ISSUE THREAD

**Issue by IceCreamYou** [pxgrid/aigis#80]
When I try to run `./node_modules/node-aigis/bin/aigis run -c ./aigis_config.yml`, I get the error: `Cannot find module 'lodash/assign'`. This started happening in version 1.1.3. I tested version 1.1.1 and 1.1.2 and in both cases the style guide is generated without errors.

**Comment by geckotang** [comment]
@IceCreamYou Thank you for reporting the problem. Could you tell me your version of node and npm?

**Comment by IceCreamYou** [comment]
Sure:

```bash
~$ node --version
v6.2.0
~$ npm --version
3.9.3
```

**Comment by geckotang** [comment]
@IceCreamYou Thanks :) Now, @nakajmg fixed this problem. Please use `node-aigis v1.1.4`.
