### ISSUE TITLE
Indent in code sample flattened.

### ISSUE THREAD

**Issue by funyapu** [pxgrid/aigis#82]
# Issue summary

Indent in code sample had been disappeared in html/jade syntax.

<pre>
/*

---
name: Flexbox
category:
  - Component/Flex
tag:
  - util

---
表組みレイアウト

```html
&lt;div data-flexbox-grid&gt;
  &lt;div&gt;
    指定なし
  &lt;/div&gt;
  &lt;div&gt;
    指定なし
  &lt;/div&gt;
&lt;/div&gt;
```
*/
</pre>

<img width="940" alt="localhost_8080_doc_styleguide_category_component_flex_index_html_" src="https://cloud.githubusercontent.com/assets/5101532/17282366/082a388e-57e0-11e6-8792-58dcb42497f9.png">
## Note
- The output for the code sample section is different from the example codes in repo.
# env

```
Node: v4.4.5
npm: 3.10.1
aigis: 1.1.4 / 1.1.2 / 1.1.0 (works in 1.0.4)
```

**Comment by geckotang** [comment]
@Funyapu Which template engine for your style guide did you use? Could you show me your `aigis_config.yml`?

Following screen shot is my test on `aigis 1.1.4` with ejs.

![image](https://cloud.githubusercontent.com/assets/683965/17282747/2ae49d48-57e4-11e6-9c61-f816766df445.png)

**Comment by Funyapu** [comment]
@geckotang Sorry for late reply. I chose `jade`.

Here is my `aigis_config.yml` just for incase.
```
##
# Styleguide tool
##
#
# The directory containing the source files to parse recursively
source: 
  - resources/assets/stylus/portal

# The directory that aigis will build to
dest: ./public/doc/styleguide

# The assets needed to build the docs
# You may put doc related assets here too: images, css, etc.
dependencies:
  - ./resources/assets/aigis/aigis_assets

# The directory containing the tempalte files to generate pages
# It must contain 'layout.xxx' and 'index.xxx' (.ejs or .jade or .hbs)
template_dir: ./resources/assets/aigis/template_jade
template_engine: jade
color_palette: false
```

**Comment by nakajmg** [comment]
I think it occurred by CSS that maybe depends on `white-space` property.

@Funyapu 
Could you check elements styles of `code` and `pre` ?

**Comment by funyapu** [comment]
Hi @nakajmg .
Sorry for late come back.

I had compared 1.1.5 and 1.0.4 and figured out it's not matter of `white-space`...
Aigis printed out 2 spaces for indent on 1.0.4, but not in 1.1.5.

## 1.0.4
<img width="1045" alt="2016-09-11 18 14 18" src="https://cloud.githubusercontent.com/assets/5101532/18416305/98f95f9e-784b-11e6-9225-067e1541bfcb.png">

## 1.1.5
<img width="1005" alt="2016-09-11 18 31 22" src="https://cloud.githubusercontent.com/assets/5101532/18416375/f80c53a4-784d-11e6-9f77-9afdadbe841f.png">


## code
``` code
  /*
 ---
 name: Normal Panel
 category:
   - Layout/Page
 ---
 ¥```html
 <div data-content-body="normal" data-content-layout="normal-panel">
   <div data-input-panel="item-edit" data-panel="">
     通常のメインコンテナ
   </div>
 </div>
 ¥```
 */
```

## conf
```
##
# Styleguide tool
##
#
# The directory containing the source files to parse recursively
source: 
  - resources/assets/stylus/portal

# The directory that aigis will build to
dest: ./public/doc/styleguide

# The assets needed to build the docs
# You may put doc related assets here too: images, css, etc.
dependencies:
  - ./resources/assets/aigis/aigis_assets

# The directory containing the tempalte files to generate pages
# It must contain 'layout.xxx' and 'index.xxx' (.ejs or .jade or .hbs)
template_dir: ./resources/assets/aigis/template_jade
template_engine: jade
color_palette: false
```

**Comment by geckotang** [comment]
@funyapu Sorry, I couldn't find the problem. If possible, I'd be grateful if you could send me your project file.

**Comment by funyapu** [comment]
Don't know why, but looks it's been fixed.
Might be because I was using `molokai` for template_theme...
