### ISSUE TITLE
Prism theme fix

### ISSUE THREAD

**Issue by legoheld** [pxgrid/aigis#89]
Themes from http://prismjs.com require a root tag with:
`code[class*="language-"],pre[class*="language-"]`
But aigis generates the codeblocks with:
`code[class*="lang-"],pre[class*="lang-"]`

Sure a search and replace on the prism theme works but would be nice to include it without modification.

**Comment by nakajmg** [comment]
Thank you for report 🙏 

I fixed it on #91 that already merged.
Also `node-aigis@1.2.0` was released 🎉 

Could you try `node-aigis@1.2.0` or `gulp-aigis@1.2.0` ?

**Comment by legoheld** [comment]
Thank you for the fix! 👍
