### ISSUE TITLE
Pass options to Aigis programmatically

### ISSUE THREAD

**Issue by clementoriol** [pxgrid/aigis#94]
Hello !
First of all, awesome work on Aigis. It's a great styleguide generator, and we really enjoy using it.

Since Aigis is usable programmatically using 
```
 var aigis = new Aigis('path/to/config.yml');
 aigis.run();
```

It would be nice to be able to pass the config as a JavaScript object instead of a string (the config path).

Something like : 
```
var config = {
  name: 'Examples Styleguide',
  source: [ './css', './demo.md' ],
  source_type: [ '.css', '.sass', '.scss', '.styl' ],
  dest: './styleguide2',
  dependencies: [ './aigis_assets', './css' ],
  index: './index.md',
  template_engine: 'ejs',
  template_dir: './template_ejs',
  log: false,
  color_palette: true,
  transform: [ 'html' ],
  timestamp_format: 'YYYY/MM/DD HH:mm',
  preview_class: 'aigis-preview',
  component_dir: './html',
  output_collection: [ 'category', 'tag' ],
  highlight: true,
  highlight_theme: 'monokai',
  lang_prefix: 'language-',
  helper_options: { disable_link_index: true }
};

 var aigis = new Aigis(config);
 aigis.run();
```

I personally needed it to be able to switch the build folder based on the current environnement.
I forked the repo and made a quick implementation of it : https://github.com/clementoriol/aigis

Two things to note 
- It might be a bit of a simple implementation, I might be missing some edge cases I don't know of
- It lacks documentation, but then again I'm not sure where to add it (the Readme is a bit sparse).

I'm opening this issue to start discussing this.
Is it something you would consider adding to Aigis ?
Should I open a Pull Request ?

Thanks

**Comment by nakajmg** [comment]
Hello!

I saw your commit on  https://github.com/clementoriol/aigis.
It's looks good for me 👍  

Could you open a Pull Request ?

**Comment by clementoriol** [comment]
Sorry guys, I totally missed the notification, opening the PR right now

**Comment by geckotang** [comment]
@clementoriol I just merged your PRs. Thanks.
