### ISSUE TITLE
Can we use pug (html template) soon?

### ISSUE THREAD

**Issue by tnyk35** [pxgrid/aigis#97]
Recently I often use pug at work, However It's not supported.
Are there plans to support in the future? I am very pleased to correspond with it.

**Comment by geckotang** [comment]
@tnyk35

> Are there plans to support in the future?

Yes, aigis will be supported [pug](https://pugjs.org/). However, If we changed the template engine from jade to pug, the change will be a breaking change. 

we want to update aigis with the following plan.

First, aigis 1.x : we will create a plugin system that you can choose a template engine freely.
Next, aigis 2.x : aigis will be supported pug and unsupported jade.

**Comment by tnyk35** [comment]
@geckotang 

Thank you very much for answering!

> we want to update aigis with the following plan.
>
>First, aigis 1.x : we will create a plugin system that you can choose a template engine freely.
>Next, aigis 2.x : aigis will be supported pug and unsupported jade.

Those plans are very nice. I'm looking forward to completing them. 
I'll continue to watch this project.
