### ISSUE TITLE
How can I run unit tests?

### ISSUE THREAD

**Issue by okmttdhr** [pxgrid/aigis#99]
I found some unit tests in this repository, but I couldn't find how to run tests with `npm scripts` nor `gulp`. How can I run and add tests when I would like to contribute?  I'd appreciate your reply. 🙇

**Comment by nakajmg** [comment]
It's [the test](https://github.com/pxgrid/aigis/tree/master/test) we wrote in past versions, unfortunately we don't have any tests for latest version...

I'd like to write a test, however I feel that it is difficult to test what to test. I'm not familiar with a testing😂

Are there any good ideas?

**Comment by okmttdhr** [comment]
It seems that it can be possible to write tests as your past versions did (I created just a sample pull request https://github.com/pxgrid/aigis/pull/103 ) 💭 

And we can follow the Single Responsibility Principle for the `what to test` problem, I think. 
(It's easier said than done though..)

reference; [What are the design principles that promote testable code? (designing testable code vs driving design through tests) - Software Engineering Stack Exchange](http://softwareengineering.stackexchange.com/questions/153410/what-are-the-design-principles-that-promote-testable-code-designing-testable-c)

**Comment by geckotang** [comment]
I just merged @okmttdhr 's PRs. Thank you.
